name: Security Audit
description: Run pnpm audit to check for dependency vulnerabilities
inputs:
  audit-level:
    description: 'Audit level: low, moderate, high, critical'
    required: false
    default: 'high'
  fail-on-vulnerabilities:
    description: 'Fail the workflow if vulnerabilities are found'
    required: false
    default: 'true'

runs:
  using: composite
  steps:
    - name: Run security audit
      shell: bash
      run: |
        echo "Running pnpm audit at ${{ inputs.audit-level }} level..."

        if [ "${{ inputs.fail-on-vulnerabilities }}" = "true" ]; then
          pnpm audit --audit-level=${{ inputs.audit-level }}
        else
          pnpm audit --audit-level=${{ inputs.audit-level }} || echo "Vulnerabilities found but not blocking"
        fi

    - name: Generate audit summary
      if: always()
      shell: bash
      run: |
        echo "## 🔒 Security Audit Results" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY

        if pnpm audit --json > audit-result.json 2>&1; then
          echo "✅ No vulnerabilities found at ${{ inputs.audit-level }} level" >> $GITHUB_STEP_SUMMARY
        else
          echo "⚠️ Vulnerabilities detected:" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY

          # Parse and display vulnerability summary
          if [ -f audit-result.json ]; then
            jq -r '.metadata.vulnerabilities | to_entries | map("- \(.key): \(.value)") | .[]' audit-result.json >> $GITHUB_STEP_SUMMARY 2>/dev/null || true
          fi
        fi
