version: 2
updates:

  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: daily
      time: "20:00"
      timezone: America/New_York
    open-pull-requests-limit: 99
    allow:
      # Allow both direct and indirect updates for all packages.
      - dependency-type: "all"
    ignore:
    # All Chai dependency major version 5 does not support common js modules
    - dependency-name: "chai"
    - dependency-name: "@types/chai"
