queue_rules:
  - name: default
    conditions:
      - "#approved-reviews-by>=1"
      - base=main

pull_request_rules:
  - name: automatic merge for main when reviewed and CI passes
    conditions:
      - label=ready-to-merge
    actions:
      queue:
        name: default
        method: squash
  - name: delete head branch after merge
    conditions:
      - merged
    actions:
      delete_head_branch: {}
  - name: ask developers to resolve conflict
    conditions:
      - conflict
      - -author~=^dependabot(|-preview)\[bot\]$
    actions:
        comment:
          message: This pull request has a conflict. Could you fix it @{{author}}?
