name: Create Docker Multi-Arch Manifest
description: Combine separate amd64 and arm64 images into a multi-arch manifest
inputs:
  image-name:
    description: 'Base image name (e.g., mitre/saf)'
    required: true
  version-tag:
    description: 'Version tag (e.g., v1.5.1 or latest or SHA)'
    required: true
  docker-username:
    description: 'DockerHub username'
    required: true
  docker-password:
    description: 'DockerHub password/token'
    required: true

runs:
  using: composite
  steps:
    - name: Login to DockerHub
      uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.4.0
      with:
        username: ${{ inputs.docker-username }}
        password: ${{ inputs.docker-password }}

    - name: Create and push multi-arch manifest
      shell: bash
      run: |
        IMAGE="${{ inputs.image-name }}"
        TAG="${{ inputs.version-tag }}"

        echo "Creating multi-arch manifest: $IMAGE:$TAG"

        # Create manifest pointing to both architecture-specific images
        docker manifest create "$IMAGE:$TAG" \
          "$IMAGE:$TAG-amd64" \
          "$IMAGE:$TAG-arm64"

        # Annotate each image with its architecture
        docker manifest annotate "$IMAGE:$TAG" "$IMAGE:$TAG-amd64" --arch amd64
        docker manifest annotate "$IMAGE:$TAG" "$IMAGE:$TAG-arm64" --arch arm64

        # Push the manifest
        docker manifest push "$IMAGE:$TAG"

        echo "✓ Multi-arch manifest created and pushed: $IMAGE:$TAG"

    - name: Verify manifest
      shell: bash
      run: |
        IMAGE="${{ inputs.image-name }}"
        TAG="${{ inputs.version-tag }}"

        echo "Verifying multi-arch manifest..."
        docker manifest inspect "$IMAGE:$TAG"
