name: Build macOS Installer
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  build-deploy:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@7088e561eb65bb68695d245aa206f005ef30921d # v4.1.0
        with:
          version: 10.18.0

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          check-latest: true
          cache: 'pnpm'

      - name: Install project dependencies
        run: pnpm install --frozen-lockfile --prod

      - name: Remove testing resources
        run: rm -rf test

      - name: npm pack
        run: npx oclif pack macos

      - name: Rename Mac Installers
        run: |
          cd dist/macos
          for file in saf-*.pkg; do
            prefix=${file%-*-*.pkg}
            suffix=${file#saf-*-*-*}
            mv "$file" "$prefix-$suffix"
          done

      - name: Upload SAF-CLI macOS Installer Artifact
        uses: actions/upload-artifact@v4
        with:
          name: SAF-CLI macOS Installer
          path: dist/macos/saf-*.pkg
