name: Draft Release

on:
  push:
    branches:
      - main

permissions:
  contents: write # required to update the draft release
  pull-requests: read # required to get information about the pull request

jobs:
  update_draft_release:
    runs-on: ubuntu-22.04
    steps:
      # Drafts your next Release notes as Pull Requests are merged into "main"
      - uses: release-drafter/release-drafter@v6
        with:
          disable-autolabeler: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
