name: Lint SAF-CLI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
     - uses: actions/checkout@v4

     - name: Install pnpm
       uses: pnpm/action-setup@7088e561eb65bb68695d245aa206f005ef30921d # v4.1.0
       with:
         version: 10.18.0

     - name: Setup Node.js
       uses: actions/setup-node@v4
       with:
        node-version: "22"
        check-latest: true
        cache: 'pnpm'

     - name: Install project dependencies
       run: pnpm install --frozen-lockfile

     - name: Run lint
       run: pnpm run lint:ci
