name: Push SAF-CLI to NPM and GPR
on:
  release:
    types: [published]

jobs:
  build-deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@7088e561eb65bb68695d245aa206f005ef30921d # v4.1.0
        with:
          version: 10.18.0

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          check-latest: true
          registry-url: "https://registry.npmjs.org"
          cache: 'pnpm'

      - name: Remove testing resources
        run: rm -rf test

      - name: Install project dependencies
        run: pnpm install --frozen-lockfile

      - name: Pack all items that are published as packages
        run: npm pack

      - name: Publish SAF CLI to NPM
        run: npm publish --access public mitre-saf-*.tgz
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # Setup .npmrc file to publish to GitHub Package Registry
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
          registry-url: 'https://npm.pkg.github.com'
          cache: 'pnpm'

      # Publish SAF CLI to GitHub Package Registry
      - name: Publish SAF CLI to GPR
        run: npm publish --access public mitre-saf-*.tgz
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
