name: Draft Release

on:
  push:
    branches:
      - main

permissions:
  contents: write # required to update the draft release
  pull-requests: read # required to get information about the pull request

jobs:
  update_draft_release:
    runs-on: ubuntu-24.04
    steps:
      - name: Update draft release notes from merged pull requests
        uses: release-drafter/release-drafter@34d80673e067bdc0c24568d3af899c216adcfaa9 # v7.7.0
