name: Run SAF-CLI E2E Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

permissions:
  contents: read

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
       platform: [ ubuntu, macos, windows ]
    runs-on: ${{ matrix.platform }}-latest
    steps:
      - name: Check out source
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up Node.js and install locked dependencies
        uses: ./.github/actions/setup-node

      - name: Install cinc-auditor on windows
        if: ${{ matrix.platform == 'windows' }}
        shell: pwsh
        run: |
          . { iwr -useb https://omnitruck.cinc.sh/install.ps1 } | iex; install -project cinc-auditor
          'C:\cinc-project\cinc-auditor\bin' >> $env:GITHUB_PATH
          'C:\cinc-project\cinc-auditor\embedded\bin' >> $env:GITHUB_PATH
          $env:Path = $env:Path + ';C:\cinc-project\cinc-auditor\bin' + ';C:\cinc-project\cinc-auditor\embedded\bin'
          cinc-auditor -v

      - name: Install cinc-auditor on ubuntu or macos
        if: ${{ matrix.platform == 'ubuntu' || matrix.platform == 'macos' }}
        run: |
          curl -L https://omnitruck.cinc.sh/install.sh | sudo bash -s -- -P cinc-auditor

      - name: Run E2E tests on ${{ matrix.platform }}
        run: |
          npm run prepack
          npm run test:ci

      - name: Smoke test to see if the CLI works with just production dependencies
        shell: bash
        run: |
          npm prune --omit=dev --ignore-scripts --no-audit --no-fund
          if stderr=$(./bin/run -v 2>&1 1>/dev/null); then
            [ -z "$stderr" ] || { printf 'Failed: received the following stderr:\n%s\n' "$stderr" >&2; exit 1; }
          else
            printf 'Failed: received a non-zero exit code when doing `saf -v`\n%s\n' "$stderr" >&2
            exit 1
          fi
