name: Track Download Metrics

on:
  schedule:
    # Run weekly on Saturdays at 3am UTC
    - cron: '0 3 * * 6'
  workflow_dispatch:

permissions:
  contents: read
  issues: write  # To create metrics issue/comment

jobs:
  track-metrics:
    name: Collect and Report Download Metrics
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Get NPM download stats
        id: npm-stats
        run: |
          PACKAGE="@mitre/saf"

          # Last week downloads
          LAST_WEEK=$(curl -s "https://api.npmjs.org/downloads/point/last-week/$PACKAGE" | jq -r '.downloads')

          # Last month downloads
          LAST_MONTH=$(curl -s "https://api.npmjs.org/downloads/point/last-month/$PACKAGE" | jq -r '.downloads')

          # All time (last year as proxy)
          LAST_YEAR=$(curl -s "https://api.npmjs.org/downloads/point/last-year/$PACKAGE" | jq -r '.downloads')

          echo "npm-week=$LAST_WEEK" >> $GITHUB_OUTPUT
          echo "npm-month=$LAST_MONTH" >> $GITHUB_OUTPUT
          echo "npm-year=$LAST_YEAR" >> $GITHUB_OUTPUT

      - name: Get Docker Hub download stats
        id: docker-stats
        run: |
          REPO="mitre/saf"

          # Docker Hub pulls (requires auth for detailed stats, using public API)
          PULLS=$(curl -s "https://hub.docker.com/v2/repositories/$REPO/" | jq -r '.pull_count')

          echo "docker-pulls=$PULLS" >> $GITHUB_OUTPUT

      - name: Get GitHub Release download stats
        id: github-stats
        run: |
          REPO="mitre/saf"

          # Get latest release asset downloads
          DOWNLOADS=$(gh api repos/$REPO/releases/latest --jq '[.assets[].download_count] | add')
          RELEASE_TAG=$(gh api repos/$REPO/releases/latest --jq '.tag_name')

          echo "release-downloads=$DOWNLOADS" >> $GITHUB_OUTPUT
          echo "release-tag=$RELEASE_TAG" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create metrics summary
        run: |
          echo "## 📊 SAF CLI Download Metrics" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Report Date**: $(date -u +%Y-%m-%d)" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY

          echo "### NPM Registry" >> $GITHUB_STEP_SUMMARY
          echo "- Last week: ${{ steps.npm-stats.outputs.npm-week }} downloads" >> $GITHUB_STEP_SUMMARY
          echo "- Last month: ${{ steps.npm-stats.outputs.npm-month }} downloads" >> $GITHUB_STEP_SUMMARY
          echo "- Last year: ${{ steps.npm-stats.outputs.npm-year }} downloads" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY

          echo "### Docker Hub" >> $GITHUB_STEP_SUMMARY
          echo "- Total pulls: ${{ steps.docker-stats.outputs.docker-pulls }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY

          echo "### GitHub Releases" >> $GITHUB_STEP_SUMMARY
          echo "- Latest release: ${{ steps.github-stats.outputs.release-tag }}" >> $GITHUB_STEP_SUMMARY
          echo "- Asset downloads: ${{ steps.github-stats.outputs.release-downloads }}" >> $GITHUB_STEP_SUMMARY

          echo "" >> $GITHUB_STEP_SUMMARY
          echo "_Metrics collected automatically every Saturday_" >> $GITHUB_STEP_SUMMARY
