name: Security Audit

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  schedule:
    # Run weekly on Mondays at 9am UTC
    - cron: '0 9 * * 1'

permissions:
  contents: read

concurrency:
  group: security-audit-${{ github.ref }}
  cancel-in-progress: true

jobs:
  dependency-audit:
    name: Dependency Security Audit
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup SAF CLI environment
        uses: ./.github/actions/setup-saf-cli
        with:
          install-deps: 'false'

      - name: Run pnpm audit (moderate level)
        run: pnpm audit --audit-level=moderate
        continue-on-error: true

      - name: Run pnpm audit (high level - blocking)
        run: pnpm audit --audit-level=high

      - name: Audit Summary
        if: always()
        run: |
          echo "## Security Audit Results" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "✓ No high or critical vulnerabilities found" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          pnpm audit --json | jq -r '.metadata | "- Total dependencies: \(.totalDependencies)\n- Vulnerabilities: \(.vulnerabilities.total)"' >> $GITHUB_STEP_SUMMARY || true
