name: Manage Stale Issues and PRs

on:
  schedule:
    # Run daily at 1am UTC
    - cron: '0 1 * * *'
  workflow_dispatch:

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    name: Mark and Close Stale Issues/PRs
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/stale@28ca1036281a5e5922ead5184a1bbf96e5fc984e # v9.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

          # Issues
          stale-issue-message: 'This issue has been automatically marked as stale because it has not had recent activity. It will be closed in 7 days if no further activity occurs. Thank you for your contributions.'
          close-issue-message: 'This issue was automatically closed due to inactivity. Please feel free to reopen if still relevant.'
          days-before-issue-stale: 90
          days-before-issue-close: 7
          stale-issue-label: 'stale'
          exempt-issue-labels: 'pinned,security,bug'

          # Pull Requests
          stale-pr-message: 'This PR has been automatically marked as stale because it has not had recent activity. It will be closed in 14 days if no further activity occurs.'
          close-pr-message: 'This PR was automatically closed due to inactivity. Please feel free to reopen if still relevant.'
          days-before-pr-stale: 60
          days-before-pr-close: 14
          stale-pr-label: 'stale'
          exempt-pr-labels: 'pinned,security,work-in-progress'

          # Rate limiting
          operations-per-run: 100
